/** Optional production server: static assets and Resend-backed contact API. No dependencies. */
import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||3000),MAX_BODY=12_000;
const hits=new Map();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8'};
const json=(res,code,obj)=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const scrub=(s,max=180)=>typeof s==='string'?s.trim().slice(0,max).replace(/[\r\n\0]/g,' '):'';
function valid(d){return d&&typeof d==='object'&&scrub(d.name,100).length>1&&scrub(d.company,120).length>1&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(scrub(d.email,160))&&['ship','crew','log'].includes(d.service)&&typeof d.details==='string'&&d.details.trim().length>=10&&d.details.length<=3000&&d.consent==='on'}
async function api(req,res){let ip=req.socket.remoteAddress||'unknown',now=Date.now(),h=hits.get(ip)||[];h=h.filter(n=>now-n<3600_000);if(h.length>=8)return json(res,429,{message:'Limite de pedidos temporariamente atingido.'});hits.set(ip,h);const origin=req.headers.origin;if(origin){try{const url=new URL(origin);if(url.host!==req.headers.host)return json(res,403,{message:'Origem não autorizada.'})}catch{return json(res,403,{message:'Origem inválida.'})}}
 let parts=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)return json(res,413,{message:'Pedido demasiado grande.'});parts.push(chunk)}let data;try{data=JSON.parse(Buffer.concat(parts).toString())}catch{return json(res,400,{message:'Formato inválido.'})}if(data.website)return json(res,200,{ok:true});if(!valid(data))return json(res,422,{message:'Preencha os campos obrigatórios e confirme o consentimento.'});if(!process.env.RESEND_API_KEY||!process.env.MAIL_FROM)return json(res,503,{message:'Serviço de e-mail não configurado.'});
 const body=[['Nome',data.name],['Empresa',data.company],['E-mail',data.email],['Telefone',data.phone],['Serviço',data.service],['Porto/local',data.port],['Navio',data.vessel],['ETA',data.eta],['Requisitos',data.details]].map(([k,v])=>`${k}: ${String(v||'').slice(0,3000)}`).join('\n');
 try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.MAIL_FROM,to:[process.env.MAIL_TO||'pedidos@wavelela.com'],reply_to:scrub(data.email),subject:`Pedido WAVELELA — ${scrub(data.service)} — ${scrub(data.company)}`,text:body})});if(!r.ok){console.error('E-mail provider error:',r.status);return json(res,502,{message:'Falha no serviço de envio.'})}h.push(now);hits.set(ip,h);return json(res,200,{ok:true})}catch(e){console.error('Delivery failed:',e.message);return json(res,502,{message:'Serviço de envio indisponível.'})}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/contact')return req.method==='POST'?api(req,res):json(res,405,{message:'Método não permitido'});if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{message:'Método não permitido'});let rel=decodeURIComponent(u.pathname).replace(/^\/+/, '')||'index.html';if(rel.endsWith('/'))rel+='index.html';const file=resolve(root,rel);if(!file.startsWith(root)||file.includes(`${sep}.`))return json(res,403,{message:'Acesso negado'});let data;try{const info=await stat(file);if(!info.isFile())throw Error('not file');data=await readFile(file)}catch{res.writeHead(404,{'content-type':'text/html; charset=utf-8'});return res.end(await readFile(resolve(root,'404.html')))}res.writeHead(200,{'content-type':types[extname(file)]||'application/octet-stream','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=()','cache-control':extname(file)==='.html'?'no-cache':'public, max-age=86400'});res.end(req.method==='HEAD'?undefined:data)}catch(e){console.error('Request failed:',e);json(res,500,{message:'Erro interno'})}});
server.listen(PORT,()=>console.log(`WAVELELA at http://localhost:${PORT}`));
