import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as sleep} from 'node:timers/promises';
const freePort=async()=>{const s=net.createServer();s.listen(0,'127.0.0.1');await once(s,'listening');const p=s.address().port;await new Promise(ok=>s.close(ok));return p};
const start=async(env)=>{const port=await freePort();const p=spawn(process.execPath,['server.js'],{cwd:new URL('../',import.meta.url).pathname,env:{...process.env,PORT:String(port),...env},stdio:['ignore','pipe','pipe']});let stderr='';p.stderr.on('data',d=>stderr+=d);let ready=false;for(let i=0;i<80;i++){if(p.exitCode!==null)break;try{const r=await fetch(`http://127.0.0.1:${port}/config.js`);ready=r.ok;break}catch{}await sleep(40)}if(!ready){p.kill();throw new Error(`server did not start: ${stderr}`)}return {url:`http://127.0.0.1:${port}`,close:async()=>{p.kill('SIGTERM');await once(p,'exit').catch(()=>{})}}};
const form=(override={})=>({requestId:crypto.randomUUID(),submittedAt:new Date().toISOString(),requesterType:'business',company:'Teste & Filhos, Lda.',name:'Maria Silva',email:'maria@example.org',phone:'+244 923 000 000',service:'ship',otherService:'',port:'Luanda',deadline:'2026-12-15',vessel:'Navio X',eta:'2026-12-14T12:00',details:'Precisamos de 12 caixas de provisões e 2 equipamentos <urgentes>.',consent:'on',website:'',...override});
const post=(url,payload,headers={})=>fetch(`${url}/api/contact`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(payload)});
test('no secrets: HTTP backend signals unconfigured instead of fake success',async()=>{const app=await start({RESEND_API_KEY:'',MAIL_FROM:''});try{const r=await post(app.url,form());assert.equal(r.status,503);assert.equal((await r.json()).ok,undefined);const assets=await fetch(app.url+'/assets/hero-port.webp');assert.equal(assets.status,200);const secret=await fetch(app.url+'/.env.example');assert.equal(secret.status,404);const config=await fetch(app.url+'/config.js');assert.equal(config.status,200)}finally{await app.close()}});
test('reject missing fields, invalid individual requests, cross origins, invalid method and bot-field',async()=>{const app=await start({RESEND_API_KEY:'test',MAIL_FROM:'Test <sender@example.org>'});try{let r=await post(app.url,form({name:'X'}));assert.equal(r.status,422);r=await post(app.url,form({requesterType:'business',company:''}));assert.equal(r.status,422);r=await post(app.url,form({website:'spam-robot'}));assert.equal(r.status,422);r=await post(app.url,form(),{Origin:'https://unknown.example'});assert.equal(r.status,403);r=await fetch(app.url+'/api/contact');assert.equal(r.status,405);}finally{await app.close()}});
test('provider mock confirms commercial recipient, professional HTML, reply-to and deduplication',async()=>{const received=[];const provider=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;received.push({headers:req.headers,payload:JSON.parse(raw)});res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({id:'provider-message-test-123'}))});provider.listen(0,'127.0.0.1');await once(provider,'listening');const providerUrl=`http://127.0.0.1:${provider.address().port}/emails`;const app=await start({NODE_ENV:'test',RESEND_TEST_ENDPOINT:providerUrl,RESEND_API_KEY:'re_test_secret',MAIL_FROM:'WAVELELA <cotacoes@wavelela.ao>'});try{const d=form();const first=await post(app.url,d);assert.equal(first.status,200);const body=await first.json();assert.equal(body.ok,true);assert.equal(body.providerAccepted,true);assert.equal(body.reference,d.requestId);assert.equal(received.length,1);const mail=received[0].payload;assert.deepEqual(mail.to,['comercial@wavelela.ao']);assert.equal(mail.reply_to,d.email);assert.match(mail.subject,/Pedido de Cotação \| Ship Chandling \| Teste & Filhos/);assert.match(mail.html,/WAVELELA/);assert.match(mail.html,/&lt;urgentes&gt;/);assert.ok(!mail.html.includes('<urgentes>'));assert.match(mail.text,/Data da submissão/);assert.equal(received[0].headers['idempotency-key'],d.requestId);
const duplicate=await post(app.url,d);assert.equal(duplicate.status,200);assert.equal((await duplicate.json()).duplicate,true);assert.equal(received.length,1);const changed=await post(app.url,{...d,details:'Pedido alterado dez caixas e cinco componentes'});assert.equal(changed.status,409);assert.equal(received.length,1);
const individual=form({requesterType:'individual',company:'',name:'Pedro Costa',email:'pedro@example.com',service:'other',otherService:'Entrega de equipamento náutico'});const personal=await post(app.url,individual);assert.equal(personal.status,200);assert.deepEqual(received[1].payload.to,['comercial@wavelela.ao']);assert.match(received[1].payload.subject,/Entrega de equipamento náutico \| Pedro Costa/);}
finally{await app.close();await new Promise(ok=>provider.close(ok))}});
test('provider rejection does not falsely acknowledge success',async()=>{const provider=http.createServer(async(req,res)=>{for await(const _ of req){}res.writeHead(403,{'content-type':'application/json'});res.end(JSON.stringify({message:'blocked'}))});provider.listen(0,'127.0.0.1');await once(provider,'listening');const app=await start({NODE_ENV:'test',RESEND_TEST_ENDPOINT:`http://127.0.0.1:${provider.address().port}/emails`,RESEND_API_KEY:'re_dummy',MAIL_FROM:'WAVELELA <cotacoes@wavelela.ao>'});try{const r=await post(app.url,form());assert.equal(r.status,502);assert.equal((await r.json()).ok,undefined)}finally{await app.close();await new Promise(ok=>provider.close(ok))}});
