import test from 'node:test';import assert from 'node:assert/strict';import {readFile,stat} from 'node:fs/promises';
const root=new URL('../',import.meta.url);let app=await readFile(new URL('../app.js',import.meta.url),'utf8');
test('all 9 website pages exist',async()=>{for(const page of ['index','empresa','servicos','ship-chandling','crew-change','suporte-logistico','contacto','privacidade','404']){const f=new URL(`../${page}.html`,import.meta.url);assert.ok((await stat(f)).isFile())}});
test('official brand mark and high-resolution illustrative assets are bundled',async()=>{for(const f of ['wavelela-mark.png','wavelela-favicon.png','hero-port.webp','hero-mobile.webp','service-supply.webp','service-crew.webp','service-logistics.webp'])assert.ok((await stat(new URL(`../assets/${f}`,import.meta.url))).size>1000)});
test('core content, consent and mobile navigation are implemented',()=>{for(const s of ['Ship Chandling','Crew Change','Suporte Logístico','aria-expanded','aria-live','type="checkbox"','privacidade.html','mailto:pedidos@wavelela.com'])assert.ok(app.includes(s),s)});
test('CSS contains responsive layouts and keyboard focus styles',async()=>{const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');for(const s of ['max-width:820px','max-width:550px','focus-visible','prefers-reduced-motion'])assert.ok(css.includes(s),s)});
test('optional server does not embed API secrets',async()=>{const server=await readFile(new URL('../server.js',import.meta.url),'utf8');assert.ok(server.includes('process.env.RESEND_API_KEY'));assert.ok(server.includes('valid(data)'));assert.ok(server.includes('MAX_BODY'))});

 test('all service cards point to working detail pages and preselected quote links',()=>{for(const k of ['ship','crew','log']){assert.ok(app.includes("?servico=${key}" )===false || app.includes('servico=${key}'));}assert.ok(app.includes('card-actions'));assert.ok(app.includes('service-quote'))});
 test('responsive mobile image and styles are available',async()=>{const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');assert.ok(css.includes('hero-mobile.webp'));assert.ok(css.includes('card-actions'));assert.ok(css.includes('coverage-art'));const logo=await stat(new URL('../assets/wavelela-mark.png',import.meta.url));assert.ok(logo.size>10000)});
